module "AGW1" {
    source = "../../../modules/application gateway"
    resource_group_name             = var.resource_group_name
    location                        = var.location
    virtual_network_name            = var.virtual_network_name
    appgw_subnet_name               = var.appgw_subnet_name
    appgw-pip                       = var.appgw-pip
    allocation_method               = var.allocation_method
    app_gateway_name                = var.app_gateway_name
    app_gateway_tier                = var.app_gateway_tier
    sku                             = var.sku
    gateway_ip_configuration        = var.gateway_ip_configuration
}

module "AGW2" {
    source = "../../../modules/application gateway"
    resource_group_name             = var.resource_group_name
    location                        = var.location
    virtual_network_name            = var.virtual_network_name
    appgw_subnet_name               = var.appgw_subnet_name1
    appgw-pip                       = var.appgw-pip1
    allocation_method               = var.allocation_method
    app_gateway_name                = var.app_gateway_name1
    app_gateway_tier                = var.app_gateway_tier
    sku                             = var.sku
    gateway_ip_configuration        = var.gateway_ip_configuration
}

module "AGW3" {
    source = "../../../modules/application gateway"
    resource_group_name             = var.resource_group_name
    location                        = var.location
    virtual_network_name            = var.virtual_network_name
    appgw_subnet_name               = var.appgw_subnet_name2
    appgw-pip                       = var.appgw-pip2
    allocation_method               = var.allocation_method
    app_gateway_name                = var.app_gateway_name2
    app_gateway_tier                = var.app_gateway_tier
    sku                             = var.sku
    gateway_ip_configuration        = var.gateway_ip_configuration
}

module "AKS1" {
  source = "../../../modules/azure kubernetes"
  aks_name                            = var.aks_name
  resource_group_name                 = var.resource_group_name
  location                            = var.location
  virtual_network_name                = var.virtual_network_name
  azurerm_subnet                      = var.azurerm_subnet
  dns_prefix                          = var.dns_prefix
  private_dns_zone_id                 = var.private_dns_zone_id
  disk_encryption_set_id              = var.disk_encryption_set_id
  kubernetes_version                  = var.kubernetes_version
  node_resource_group                 = var.node_resource_group
  private_cluster_public_fqdn_enabled        = var.private_cluster_public_fqdn_enabled
  sku_tier                            = var.sku_tier
  default_node_pool_name                         = var.default_node_pool_name
  default_node_pool_node_count                   = var.default_node_pool_node_count
  default_node_pool_vm_size                      = var.default_node_pool_vm_size
  default_node_pool_enable_auto_scaling          = var.default_node_pool_enable_auto_scaling
  default_node_pool_enable_host_encryption       = var.default_node_pool_enable_host_encryption
  default_node_pool_enable_node_public_ip        = var.default_node_pool_enable_node_public_ip
  default_node_pool_fips_enabled                 = var.default_node_pool_fips_enabled
  default_node_pool_kubelet_disk_type            = var.default_node_pool_kubelet_disk_type
  default_node_pool_max_pods                     = var.default_node_pool_max_count
  default_node_pool_message_of_the_day           = var.default_node_pool_message_of_the_day
  default_node_pool_node_public_ip_prefix_id     = var.default_node_pool_node_public_ip_prefix_id
  default_node_pool_node_labels                  = var.default_node_pool_node_labels
  default_node_pool_only_critical_addons_enabled = var.default_node_pool_only_critical_addons_enabled
  default_node_pool_orchestrator_version         = var.default_node_pool_orchestrator_version 
  default_node_pool_os_disk_size_gb              = var.default_node_pool_os_disk_size_gb  
  default_node_pool_os_disk_type                 = var.default_node_pool_os_disk_type    
  default_node_pool_os_sku                       = var.default_node_pool_os_sku 
  default_node_pool_proximity_placement_group_id = var.default_node_pool_proximity_placement_group_id
  default_node_pool_scale_down_mode              = var.default_node_pool_scale_down_mode
  default_node_pool_zones                        = var.default_node_pool_zones 
  default_node_pool_type                         = var.default_node_pool_type  
  default_node_pool_ultra_ssd_enabled            = var.default_node_pool_ultra_ssd_enabled   
  default_node_pool_max_count                    = var.default_node_pool_max_count   
  default_node_pool_min_count                    = var.default_node_pool_min_count  
  default_node_pool_kubelet_config               = var.default_node_pool_kubelet_config  
  default_node_pool_linux_os_config              = var.default_node_pool_linux_os_config  
  default_node_pool_upgrade_settings             = var.default_node_pool_upgrade_settings
  aci_connector_linux                            = var.aci_connector_linux 
  azure_policy_enabled                           = var.azure_policy_enabled
  http_application_routing_enabled               = var.http_application_routing_enabled   
  edge_zone                                      = var.edge_zone
  workload_identity_enabled                      = var.workload_identity_enabled 
  oidc_issuer_enabled                            = var.oidc_issuer_enabled    
  auto_scaler_profile                            = var.auto_scaler_profile
  maintenance_window                             = var.maintenance_window
  linux_profile                                  = var.linux_profile
  network_profile                                = var.network_profile
  azure_active_directory_role_based_access_control =var.azure_active_directory_role_based_access_control
  app_gateway_id                                   = module.AGW1.id

}

module "AKS2" {
  source = "../../../modules/azure kubernetes"
  depends_on = [ module.AKS1 ]
  aks_name                            = var.aks_name1
  resource_group_name                 = var.resource_group_name
  location                            = var.location
  virtual_network_name                = var.virtual_network_name
  azurerm_subnet                      = var.azurerm_subnet1
  dns_prefix                          = var.dns_prefix1
  private_dns_zone_id                 = var.private_dns_zone_id
  disk_encryption_set_id              = var.disk_encryption_set_id
  kubernetes_version                  = var.kubernetes_version
  node_resource_group                 = var.node_resource_group1
  private_cluster_public_fqdn_enabled        = var.private_cluster_public_fqdn_enabled
  sku_tier                            = var.sku_tier
  default_node_pool_name                         = var.default_node_pool_name
  default_node_pool_node_count                   = var.default_node_pool_node_count
  default_node_pool_vm_size                      = var.default_node_pool_vm_size
  default_node_pool_enable_auto_scaling          = var.default_node_pool_enable_auto_scaling
  default_node_pool_enable_host_encryption       = var.default_node_pool_enable_host_encryption
  default_node_pool_enable_node_public_ip        = var.default_node_pool_enable_node_public_ip
  default_node_pool_fips_enabled                 = var.default_node_pool_fips_enabled
  default_node_pool_kubelet_disk_type            = var.default_node_pool_kubelet_disk_type
  default_node_pool_max_pods                     = var.default_node_pool_max_count
  default_node_pool_message_of_the_day           = var.default_node_pool_message_of_the_day
  default_node_pool_node_public_ip_prefix_id     = var.default_node_pool_node_public_ip_prefix_id
  default_node_pool_node_labels                  = var.default_node_pool_node_labels
  default_node_pool_only_critical_addons_enabled = var.default_node_pool_only_critical_addons_enabled
  default_node_pool_orchestrator_version         = var.default_node_pool_orchestrator_version 
  default_node_pool_os_disk_size_gb              = var.default_node_pool_os_disk_size_gb  
  default_node_pool_os_disk_type                 = var.default_node_pool_os_disk_type    
  default_node_pool_os_sku                       = var.default_node_pool_os_sku 
  default_node_pool_proximity_placement_group_id = var.default_node_pool_proximity_placement_group_id
  default_node_pool_scale_down_mode              = var.default_node_pool_scale_down_mode
  default_node_pool_zones                        = var.default_node_pool_zones 
  default_node_pool_type                         = var.default_node_pool_type  
  default_node_pool_ultra_ssd_enabled            = var.default_node_pool_ultra_ssd_enabled   
  default_node_pool_max_count                    = var.default_node_pool_max_count   
  default_node_pool_min_count                    = var.default_node_pool_min_count  
  default_node_pool_kubelet_config               = var.default_node_pool_kubelet_config  
  default_node_pool_linux_os_config              = var.default_node_pool_linux_os_config  
  default_node_pool_upgrade_settings             = var.default_node_pool_upgrade_settings
  aci_connector_linux                            = var.aci_connector_linux 
  azure_policy_enabled                           = var.azure_policy_enabled
  http_application_routing_enabled               = var.http_application_routing_enabled   
  edge_zone                                      = var.edge_zone
  workload_identity_enabled                      = var.workload_identity_enabled 
  oidc_issuer_enabled                            = var.oidc_issuer_enabled    
  auto_scaler_profile                            = var.auto_scaler_profile
  maintenance_window                             = var.maintenance_window
  linux_profile                                  = var.linux_profile
  network_profile                                = var.network_profile
  azure_active_directory_role_based_access_control =var.azure_active_directory_role_based_access_control
  app_gateway_id                                   = module.AGW2.id
  
}

module "AKS3" {
  source = "../../../modules/azure kubernetes"
  depends_on = [ module.AKS2 ]
  aks_name                            = var.aks_name2
  resource_group_name                 = var.resource_group_name
  location                            = var.location
  virtual_network_name                = var.virtual_network_name
  azurerm_subnet                      = var.azurerm_subnet2
  dns_prefix                          = var.dns_prefix2
  private_dns_zone_id                 = var.private_dns_zone_id
  disk_encryption_set_id              = var.disk_encryption_set_id
  kubernetes_version                  = var.kubernetes_version
  node_resource_group                 = var.node_resource_group2
  private_cluster_public_fqdn_enabled        = var.private_cluster_public_fqdn_enabled
  sku_tier                            = var.sku_tier
  default_node_pool_name                         = var.default_node_pool_name
  default_node_pool_node_count                   = var.default_node_pool_node_count
  default_node_pool_vm_size                      = var.default_node_pool_vm_size
  default_node_pool_enable_auto_scaling          = var.default_node_pool_enable_auto_scaling
  default_node_pool_enable_host_encryption       = var.default_node_pool_enable_host_encryption
  default_node_pool_enable_node_public_ip        = var.default_node_pool_enable_node_public_ip
  default_node_pool_fips_enabled                 = var.default_node_pool_fips_enabled
  default_node_pool_kubelet_disk_type            = var.default_node_pool_kubelet_disk_type
  default_node_pool_max_pods                     = var.default_node_pool_max_count
  default_node_pool_message_of_the_day           = var.default_node_pool_message_of_the_day
  default_node_pool_node_public_ip_prefix_id     = var.default_node_pool_node_public_ip_prefix_id
  default_node_pool_node_labels                  = var.default_node_pool_node_labels
  default_node_pool_only_critical_addons_enabled = var.default_node_pool_only_critical_addons_enabled
  default_node_pool_orchestrator_version         = var.default_node_pool_orchestrator_version 
  default_node_pool_os_disk_size_gb              = var.default_node_pool_os_disk_size_gb  
  default_node_pool_os_disk_type                 = var.default_node_pool_os_disk_type    
  default_node_pool_os_sku                       = var.default_node_pool_os_sku 
  default_node_pool_proximity_placement_group_id = var.default_node_pool_proximity_placement_group_id
  default_node_pool_scale_down_mode              = var.default_node_pool_scale_down_mode
  default_node_pool_zones                        = var.default_node_pool_zones 
  default_node_pool_type                         = var.default_node_pool_type  
  default_node_pool_ultra_ssd_enabled            = var.default_node_pool_ultra_ssd_enabled   
  default_node_pool_max_count                    = var.default_node_pool_max_count   
  default_node_pool_min_count                    = var.default_node_pool_min_count  
  default_node_pool_kubelet_config               = var.default_node_pool_kubelet_config  
  default_node_pool_linux_os_config              = var.default_node_pool_linux_os_config  
  default_node_pool_upgrade_settings             = var.default_node_pool_upgrade_settings
  aci_connector_linux                            = var.aci_connector_linux 
  azure_policy_enabled                           = var.azure_policy_enabled
  http_application_routing_enabled               = var.http_application_routing_enabled   
  edge_zone                                      = var.edge_zone
  workload_identity_enabled                      = var.workload_identity_enabled 
  oidc_issuer_enabled                            = var.oidc_issuer_enabled    
  auto_scaler_profile                            = var.auto_scaler_profile
  maintenance_window                             = var.maintenance_window
  linux_profile                                  = var.linux_profile
  network_profile                                = var.network_profile
  azure_active_directory_role_based_access_control =var.azure_active_directory_role_based_access_control
  app_gateway_id                                   = module.AGW3.id
}